base_url = "https://blog.ar-ms.me/"

compile_sass = true
build_search_index = false
title = "Abdul Rahman Sibahi"
description = "Musings"
default_language = "en"

[markdown]
highlight_code = true
highlight_theme = "inspired-github"

extra_syntaxes_and_themes = ["syntax"]

bottom_footnotes = true

[extra]

blurp = "Architect and hobbyist. Bad at websites and witty bios."
links = [
    { title = "Mail", href = "mailto:a.sibahi@gmail.com" },
    # Hopefully one day switching to own domain and Migadu.
    { title = "Twitter", href = "https://x.com/@asibahi" },
    # { title = "Instagram", href = "https://www.instagram.com/asibahi" },
    { title = "typo.social", href = "https://typo.social/@asibahi" },
    { title = "SourceHut", href = "https://sr.ht/~asibahi/"},
    { title = "GitHub", href = "https://github.com/asibahi" }
]
